version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      -"3307:${DATABASE_PORT}"
    volumes:
      - db_data:/var/lib/mysql
  
  app:
    build: .
    container_name: python_app
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    command: python mysql_connect.py

volumes:
  db_data: